package pojo;
// Generated Dec 26, 2016 8:11:13 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer id;
     private String name;
     private double price;
     private int amount;
     private String image;
     private int categoryId;
     private Date createDate;
     private boolean state;
     private byte public_;

    public Product() {
    }

	
    public Product(String name, double price, int amount, int categoryId, boolean state, byte public_) {
        this.name = name;
        this.price = price;
        this.amount = amount;
        this.categoryId = categoryId;
        this.state = state;
        this.public_ = public_;
    }
    public Product(String name, double price, int amount, String image, int categoryId, Date createDate, boolean state, byte public_) {
       this.name = name;
       this.price = price;
       this.amount = amount;
       this.image = image;
       this.categoryId = categoryId;
       this.createDate = createDate;
       this.state = state;
       this.public_ = public_;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public int getAmount() {
        return this.amount;
    }
    
    public void setAmount(int amount) {
        this.amount = amount;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public int getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public boolean isState() {
        return this.state;
    }
    
    public void setState(boolean state) {
        this.state = state;
    }
    public byte getPublic_() {
        return this.public_;
    }
    
    public void setPublic_(byte public_) {
        this.public_ = public_;
    }




}


